import { useState, useMemo, useCallback } from 'react';
import { Calculator, CheckCircle, XCircle, AlertTriangle, Info, Download } from 'lucide-react';
import { calculateOrbitalLifetime, orbitalPeriod, orbitalVelocity, type LifetimeResult } from '@/lib/orbital';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine } from 'recharts';

const presets = [
  { label: 'CubeSat (3U)', mass: 4, area: 0.03, desc: '3U CubeSat, 4kg' },
  { label: 'Small Sat', mass: 50, area: 0.25, desc: '50kg, 0.25m²' },
  { label: 'Starlink-class', mass: 260, area: 3.4, desc: '260kg, 3.4m²' },
  { label: 'Large (1t)', mass: 1000, area: 5, desc: '1000kg, 5m²' },
];

function RiskBadge({ level }: { level: LifetimeResult['riskLevel'] }) {
  const config = {
    low: { border: 'border-white/20', text: 'text-white/70', label: 'LOW RISK' },
    medium: { border: 'border-white/30', text: 'text-white/80', label: 'MEDIUM' },
    high: { border: 'border-white/50', text: 'text-white', label: 'HIGH RISK' },
    critical: { border: 'border-white', text: 'text-white', label: 'CRITICAL' },
  }[level];

  return (
    <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-bold border ${config.border} ${config.text} bg-white/[0.03]`}>
      {config.label}
    </span>
  );
}

function generateReport(
  altitude: number, mass: number, area: number, dragCd: number,
  solar: string, result: LifetimeResult
): string {
  const now = new Date().toISOString().split('T')[0];
  return `
================================================================================
                    UPAGRAHA — ORBITAL LIFETIME COMPLIANCE REPORT
================================================================================
Generated: ${now}
Platform:  https://www.upagraha.com

INPUT PARAMETERS
─────────────────────────────────────────────────────────────────────────────────
  Orbital Altitude:      ${altitude} km
  Satellite Mass:        ${mass} kg
  Cross-Section Area:    ${area} m²
  Area-to-Mass Ratio:    ${(area / mass).toFixed(6)} m²/kg
  Drag Coefficient:      ${dragCd}
  Solar Activity:        ${solar}
  Orbital Period:        ${(orbitalPeriod(altitude) / 60).toFixed(1)} min
  Orbital Velocity:      ${orbitalVelocity(altitude).toFixed(2)} km/s

RESULTS
─────────────────────────────────────────────────────────────────────────────────
  Estimated Lifetime:    ${result.lifetimeYears < 1 ? `${result.lifetimeDays} days` : result.lifetimeYears > 100 ? '100+ years' : `${result.lifetimeYears.toFixed(2)} years (${result.lifetimeDays} days)`}
  Risk Level:            ${result.riskLevel.toUpperCase()}

REGULATORY COMPLIANCE
─────────────────────────────────────────────────────────────────────────────────
  FCC 5-Year Rule:       ${result.meetsComplianceFCC ? 'COMPLIANT ✓' : 'NON-COMPLIANT ✗'}
    Requirement: Satellites must deorbit within 5 years of mission end.
    Reference:   47 CFR § 25.114(d)(14), adopted September 2022.

  ESA 25-Year Guideline: ${result.meetsComplianceESA ? 'COMPLIANT ✓' : 'NON-COMPLIANT ✗'}
    Requirement: Debris mitigation guidelines recommend max 25-year orbital lifetime.
    Reference:   ESA Space Debris Mitigation Compliance Verification Guidelines.

ALTITUDE DECAY PROFILE
─────────────────────────────────────────────────────────────────────────────────
${result.decayProfile.map(p => `  Year ${p.year.toFixed(1).padStart(6)}  →  ${p.altitude.toFixed(1).padStart(8)} km`).join('\n')}

DISCLAIMER
─────────────────────────────────────────────────────────────────────────────────
  This report uses simplified atmospheric and drag models for estimation purposes.
  Results are approximate and should not be used for operational mission planning.
  For precise calculations, use NASA DAS (Debris Assessment Software) or ESA DRAMA.

  Solar activity conditions significantly affect atmospheric density and therefore
  orbital lifetime estimates. This report represents a single-condition estimate.

================================================================================
  Report generated by Upagraha (https://www.upagraha.com)
  Open-source space debris monitoring platform.
================================================================================
`.trim();
}

export default function LifetimeCalculator() {
  const [altitude, setAltitude] = useState(500);
  const [mass, setMass] = useState(50);
  const [area, setArea] = useState(0.25);
  const [dragCd, setDragCd] = useState(2.2);
  const [solar, setSolar] = useState<'low' | 'moderate' | 'high'>('moderate');

  const result = useMemo(() => {
    if (altitude < 150 || altitude > 2000 || mass <= 0 || area <= 0) return null;
    return calculateOrbitalLifetime(altitude, area / mass, dragCd, solar);
  }, [altitude, mass, area, dragCd, solar]);

  const period = orbitalPeriod(altitude);
  const velocity = orbitalVelocity(altitude);

  const handleExport = useCallback(() => {
    if (!result) return;
    const text = generateReport(altitude, mass, area, dragCd, solar, result);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `upagraha-lifetime-report-${altitude}km-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [result, altitude, mass, area, dragCd, solar]);

  return (
    <div className="min-h-screen pt-24 pb-16 grain">
      <div className="max-w-7xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/[0.04] border border-white/[0.08] text-white/50 text-xs font-medium mb-4">
            <Calculator className="w-3.5 h-3.5" />
            Free Tool
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-white mb-4 tracking-tight">
            Orbital Lifetime Calculator
          </h1>
          <p className="text-white/35 max-w-2xl mx-auto">
            Estimate how long a satellite will remain in orbit before atmospheric reentry.
            Check compliance with FCC 5-year deorbit rule and ESA 25-year guideline.
          </p>
        </div>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Input Panel */}
          <div className="lg:col-span-1 space-y-5">
            <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-5">
              <h3 className="text-xs font-medium text-white/50 uppercase tracking-wider mb-3">Presets</h3>
              <div className="grid grid-cols-2 gap-2">
                {presets.map((p) => (
                  <button
                    key={p.label}
                    onClick={() => { setMass(p.mass); setArea(p.area); }}
                    className="text-left px-3 py-2.5 rounded-lg bg-white/[0.02] hover:bg-white/[0.06] border border-white/[0.06] hover:border-white/[0.12] transition-all text-xs"
                  >
                    <div className="text-white font-medium">{p.label}</div>
                    <div className="text-white/30">{p.desc}</div>
                  </button>
                ))}
              </div>
            </div>

            <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-5 space-y-5">
              <h3 className="text-xs font-medium text-white/50 uppercase tracking-wider">Parameters</h3>

              <div>
                <label className="flex justify-between text-sm text-white/40 mb-2">
                  <span>Orbital Altitude</span>
                  <span className="text-white font-mono text-xs">{altitude} km</span>
                </label>
                <input
                  type="range" min={150} max={2000} value={altitude}
                  onChange={(e) => setAltitude(Number(e.target.value))}
                  className="w-full accent-white"
                />
                <div className="flex justify-between text-[10px] text-white/20 mt-1">
                  <span>150 km</span><span>2000 km</span>
                </div>
              </div>

              <div>
                <label className="flex justify-between text-sm text-white/40 mb-2">
                  <span>Mass</span>
                  <span className="text-white font-mono text-xs">{mass} kg</span>
                </label>
                <input
                  type="number" value={mass} onChange={(e) => setMass(Number(e.target.value))}
                  min={0.1} step={1}
                  className="w-full bg-white/[0.03] border border-white/[0.08] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-white/20 transition-colors"
                />
              </div>

              <div>
                <label className="flex justify-between text-sm text-white/40 mb-2">
                  <span>Cross-Section</span>
                  <span className="text-white font-mono text-xs">{area} m²</span>
                </label>
                <input
                  type="number" value={area} onChange={(e) => setArea(Number(e.target.value))}
                  min={0.001} step={0.01}
                  className="w-full bg-white/[0.03] border border-white/[0.08] rounded-lg px-3 py-2 text-white text-sm focus:outline-none focus:border-white/20 transition-colors"
                />
              </div>

              <div>
                <label className="flex justify-between text-sm text-white/40 mb-2">
                  <span>Drag Coefficient</span>
                  <span className="text-white font-mono text-xs">{dragCd}</span>
                </label>
                <input
                  type="range" min={1.5} max={3.0} step={0.1} value={dragCd}
                  onChange={(e) => setDragCd(Number(e.target.value))}
                  className="w-full accent-white"
                />
              </div>

              <div>
                <label className="text-sm text-white/40 mb-2 block">Solar Activity</label>
                <div className="grid grid-cols-3 gap-2">
                  {(['low', 'moderate', 'high'] as const).map((level) => (
                    <button
                      key={level}
                      onClick={() => setSolar(level)}
                      className={`px-3 py-2 rounded-lg text-xs font-medium border transition-all ${
                        solar === level
                          ? 'bg-white/10 border-white/20 text-white'
                          : 'bg-white/[0.02] border-white/[0.06] text-white/40 hover:border-white/10'
                      }`}
                    >
                      {level.charAt(0).toUpperCase() + level.slice(1)}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-5">
              <h3 className="text-xs font-medium text-white/50 uppercase tracking-wider mb-3">Orbital Info</h3>
              <div className="space-y-2.5 text-sm">
                <div className="flex justify-between">
                  <span className="text-white/30">Period</span>
                  <span className="text-white font-mono text-xs">{(period / 60).toFixed(1)} min</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/30">Velocity</span>
                  <span className="text-white font-mono text-xs">{velocity.toFixed(2)} km/s</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/30">Orbits/Day</span>
                  <span className="text-white font-mono text-xs">{(86400 / period).toFixed(1)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-white/30">A/m Ratio</span>
                  <span className="text-white font-mono text-xs">{(area / mass).toFixed(4)} m²/kg</span>
                </div>
              </div>
            </div>
          </div>

          {/* Results */}
          <div className="lg:col-span-2 space-y-5">
            {result ? (
              <>
                <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-6">
                  <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
                    <div>
                      <div className="text-white/30 text-xs uppercase tracking-wider mb-1">Estimated Orbital Lifetime</div>
                      <div className="text-4xl font-bold text-white tracking-tight">
                        {result.lifetimeYears < 1
                          ? `${result.lifetimeDays} days`
                          : result.lifetimeYears > 100
                            ? '100+ years'
                            : `${result.lifetimeYears.toFixed(1)} years`}
                      </div>
                    </div>
                    <div className="flex items-center gap-3">
                      <RiskBadge level={result.riskLevel} />
                      <button
                        onClick={handleExport}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white/[0.04] border border-white/[0.08] text-white/60 hover:text-white hover:border-white/20 text-xs font-medium transition-all"
                      >
                        <Download className="w-3.5 h-3.5" />
                        Export
                      </button>
                    </div>
                  </div>

                  <div className="grid sm:grid-cols-2 gap-3">
                    <div className={`flex items-start gap-3 p-4 rounded-lg border ${
                      result.meetsComplianceFCC
                        ? 'bg-white/[0.02] border-white/[0.08]'
                        : 'bg-white/[0.04] border-white/[0.15]'
                    }`}>
                      {result.meetsComplianceFCC
                        ? <CheckCircle className="w-5 h-5 text-white/40 shrink-0 mt-0.5" />
                        : <XCircle className="w-5 h-5 text-white shrink-0 mt-0.5" />}
                      <div>
                        <div className={`text-sm font-medium ${result.meetsComplianceFCC ? 'text-white/60' : 'text-white'}`}>
                          FCC 5-Year Rule
                        </div>
                        <div className="text-xs text-white/30 mt-1">
                          {result.meetsComplianceFCC
                            ? 'Compliant — deorbits within 5 years'
                            : `Non-compliant — ${result.lifetimeYears.toFixed(1)}y exceeds 5y limit`}
                        </div>
                      </div>
                    </div>

                    <div className={`flex items-start gap-3 p-4 rounded-lg border ${
                      result.meetsComplianceESA
                        ? 'bg-white/[0.02] border-white/[0.08]'
                        : 'bg-white/[0.04] border-white/[0.15]'
                    }`}>
                      {result.meetsComplianceESA
                        ? <CheckCircle className="w-5 h-5 text-white/40 shrink-0 mt-0.5" />
                        : <XCircle className="w-5 h-5 text-white shrink-0 mt-0.5" />}
                      <div>
                        <div className={`text-sm font-medium ${result.meetsComplianceESA ? 'text-white/60' : 'text-white'}`}>
                          ESA 25-Year Guideline
                        </div>
                        <div className="text-xs text-white/30 mt-1">
                          {result.meetsComplianceESA
                            ? 'Compliant — deorbits within 25 years'
                            : `Non-compliant — ${result.lifetimeYears.toFixed(1)}y exceeds 25y guideline`}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {result.decayProfile.length > 1 && (
                  <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-6">
                    <h3 className="text-white font-medium text-sm mb-4">Altitude Decay Profile</h3>
                    <div className="h-64">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={result.decayProfile}>
                          <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" />
                          <XAxis
                            dataKey="year"
                            stroke="rgba(255,255,255,0.15)"
                            tick={{ fill: 'rgba(255,255,255,0.3)', fontSize: 11 }}
                            label={{ value: 'Years', position: 'insideBottom', offset: -5, fill: 'rgba(255,255,255,0.25)' }}
                          />
                          <YAxis
                            stroke="rgba(255,255,255,0.15)"
                            tick={{ fill: 'rgba(255,255,255,0.3)', fontSize: 11 }}
                            label={{ value: 'Altitude (km)', angle: -90, position: 'insideLeft', fill: 'rgba(255,255,255,0.25)' }}
                          />
                          <Tooltip
                            contentStyle={{
                              backgroundColor: '#111',
                              border: '1px solid rgba(255,255,255,0.1)',
                              borderRadius: '8px',
                              color: '#fff',
                              fontSize: 12,
                            }}
                            formatter={(value: unknown) => [`${Number(value).toFixed(1)} km`, 'Altitude']}
                            labelFormatter={(label: unknown) => `Year ${Number(label).toFixed(1)}`}
                          />
                          <ReferenceLine y={120} stroke="rgba(255,255,255,0.3)" strokeDasharray="5 5" label={{ value: 'Reentry ~120km', fill: 'rgba(255,255,255,0.4)', fontSize: 10 }} />
                          <Line type="monotone" dataKey="altitude" stroke="#ffffff" strokeWidth={1.5} dot={false} />
                        </LineChart>
                      </ResponsiveContainer>
                    </div>
                  </div>
                )}

                <div className="flex items-start gap-3 p-4 bg-white/[0.02] border border-white/[0.06] rounded-xl">
                  <Info className="w-4 h-4 text-white/30 shrink-0 mt-0.5" />
                  <div className="text-xs text-white/25 leading-relaxed">
                    <span className="text-white/50 font-medium">Disclaimer:</span> Simplified atmospheric
                    and drag models. Not for operational mission planning. Use NASA DAS or ESA DRAMA for precise calculations.
                  </div>
                </div>
              </>
            ) : (
              <div className="bg-white/[0.02] border border-white/[0.06] rounded-xl p-12 text-center">
                <AlertTriangle className="w-10 h-10 text-white/20 mx-auto mb-4" />
                <p className="text-white/30 text-sm">
                  Enter valid parameters (altitude 150–2000 km).
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
